name: Update USGS River Conditions
run-name: Update USGS River Conditions


on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # runs daily at 12:00 UTC

permissions:
  contents: write

jobs:
  update-usgs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install httpx

      - name: Run USGS pipeline
        env:
          PYTHONPATH: src
        run: |
          python usgs_pipeline.py

      
      - name: Commit updated river conditions
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add site_snippets/chattahoochee_conditions.html

          if git diff --cached --quiet; then
            echo "No river condition changes to commit"
          else
            git commit -m "Update USGS river conditions"
            git pull --rebase origin main
            git push
          fi
